version: '3'

services:
  app:
    image: com.tonyp.dictionarykotlin/meaning-app-ktor:0.1
    ports:
      - "8080:8080"
    depends_on:
      - fluent-bit
      - psql
      - keycloak
    environment:
      - LOGS_FB_HOSTS=fluent-bit
      - LOGS_FB_PORT=24224

  keycloak:
    image: jboss/keycloak
    container_name: keycloak
    ports:
      - "8081:8080"
      - "8082:9990"
    volumes:
      - ./keycloak:/tmp
    environment:
      KEYCLOAK_USER: dictionary
      KEYCLOAK_PASSWORD: dictionary
      KEYCLOAK_IMPORT: "/tmp/realm-export.json"

  psql:
    image: postgres
    container_name: psql
    volumes:
      - ./psql:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    expose:
      - "5432"
    environment:
      POSTGRES_DB: dictionary
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dictionary
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5

  fluent-bit:
    container_name: fluent-bit
    image: fluent/fluent-bit
    ports:
      - "24224:24224"
      - "24224:24224/udp"
      - "2020:2020"
    environment:
      - opensearch_host=opensearch
      - opensearch_user=admin
      - opensearch_pass=admin
    volumes:
      - ./fluent-bit-config/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      - ./fluent-bit-config/parsers.conf:/fluent-bit/etc/parsers.conf

  opensearch:
    container_name: opensearch
    image: opensearchproject/opensearch:latest
    environment:
      - discovery.type=single-node
      - http.port=9200
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ports:
      - '9200:9200'
      - '9600:9600'
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    volumes:
      - opensearch-data:/usr/share/opensearch/data

  dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: opensearch-dashboards
    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      OPENSEARCH_HOSTS: '["https://opensearch:9200"]'
    depends_on:
      - opensearch

volumes:
  opensearch-data: