ktor:
  development: true
  deployment:
    port: 8080
  watch:
    - classes
    - resources
  application:
    modules:
      - "com.tonyp.dictionarykotlin.meaning.app.ApplicationKt.module"
  urls:
    - "http://127.0.0.1:8080/"
    - "http://0.0.0.0:8080/"
dictionary:
  repository:
    test: in-memory
    prod: psql
    psql:
      url: "jdbc:postgresql://psql:5432/dictionary"
      schema: dictionary
      user: postgres
      password: dictionary
jwt:
  issuer: "http://localhost:8081/auth/realms/dictionary-meanings"
  audience: "meaning-users"
  realm: "dictionary-meanings"
  clientId: "dictionary-meanings-service"
  certUrl: "http://localhost:8081/auth/realms/dictionary-meanings/protocol/openid-connect/certs"