ktor:
  development: true
  deployment:
    port: 8080
  watch:
    - classes
    - resources
  application:
    modules:
      - "com.tonyp.dictionarykotlin.meaning.app.ApplicationKt.module"
  urls:
    - "http://127.0.0.1:8080/"
    - "http://0.0.0.0:8080/"
dictionary:
  repository:
    test: in-memory
    prod: psql
    psql:
      url: "jdbc:postgresql://localhost:5432/dictionary"
      schema: dictionary
      user: postgres
      password: dictionary
